run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - revive
    - dupl
    - unconvert
    - prealloc
    - goconst
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
