run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - gosimple
    - revive
  disable:
    - unused  # Disable unused during migration phase
