//go:build e2e

package harness

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/stretchr/testify/require"
)

// The helpers in this file resolve the demo compose stack's own coordinates and
// are used only by the client suites. What the Velero suite shares takes its
// client and bucket as parameters and lives in stored.go and atrest.go.

// BackendClient talks to MinIO directly, bypassing the proxy. It is how a suite
// proves objects are stored encrypted: everything it reads is exactly what is on
// disk in the backend.
func BackendClient(t *testing.T) *s3.Client {
	t.Helper()
	e := DemoStack(t)
	return s3Client(t, e.Get(t, "S3EP_BACKEND_ENDPOINT"),
		e.Get(t, "S3EP_BACKEND_ACCESS_KEY"), e.Get(t, "S3EP_BACKEND_SECRET_KEY"), e.Get(t, "S3EP_REGION"))
}

// ProxyClient talks to the proxy's TLS listener with the client credentials the
// demo configuration carries. A suite uses it to read back what its client
// wrote, and to set up an object its client cannot write at all.
func ProxyClient(t *testing.T) *s3.Client {
	t.Helper()
	e := DemoStack(t)
	return s3Client(t, e.Get(t, "S3EP_TLS_ENDPOINT"),
		e.Get(t, "S3EP_ACCESS_KEY"), e.Get(t, "S3EP_SECRET_KEY"), e.Get(t, "S3EP_REGION"))
}

func s3Client(t *testing.T, endpoint, accessKey, secretKey, region string) *s3.Client {
	t.Helper()
	cfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(accessKey, secretKey, "")),
		awsconfig.WithRegion(region),
		awsconfig.WithHTTPClient(caTrustingHTTPClient(t)),
	)
	require.NoError(t, err)
	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
	})
}

// caTrustingHTTPClient trusts the CA generated by test/ssl-setup/gen-certs.sh.
// Verification is deliberately on, for the same reason CACert gives.
func caTrustingHTTPClient(t *testing.T) *http.Client {
	t.Helper()
	pemBytes, err := os.ReadFile(CACert(t))
	require.NoError(t, err)
	pool := x509.NewCertPool()
	require.True(t, pool.AppendCertsFromPEM(pemBytes), "test CA is not parseable")

	return &http.Client{
		Timeout: 10 * time.Minute,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12},
		},
	}
}

// ProxyETag returns the entity tag the proxy answers on HEAD, unquoted. It is
// what the ETag decision of ADR 0010 D12 is about, and what a suite compares
// against the backend's own tag.
func ProxyETag(t *testing.T, ctx context.Context, bucket, key string) string {
	t.Helper()
	head, err := ProxyClient(t).HeadObject(ctx, &s3.HeadObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(key),
	})
	require.NoErrorf(t, err, "HEAD %s/%s through the proxy", bucket, key)
	return strings.Trim(aws.ToString(head.ETag), `"`)
}

// EnsureBucket creates a bucket through the proxy if it is not there, and
// registers its removal. A suite's own client drives the bucket lifecycle in the
// case that is about the lifecycle; everywhere else the bucket is setup.
func EnsureBucket(t *testing.T, ctx context.Context, bucket string) {
	t.Helper()
	client := ProxyClient(t)
	_, err := client.HeadBucket(ctx, &s3.HeadBucketInput{Bucket: aws.String(bucket)})
	if err != nil {
		_, err = client.CreateBucket(ctx, &s3.CreateBucketInput{Bucket: aws.String(bucket)})
		require.NoErrorf(t, err, "creating bucket %s through the proxy", bucket)
	}
	t.Cleanup(func() { EmptyAndDeleteBucket(t, context.Background(), bucket) })
}

// EmptyBucket removes every object and every open multipart upload of a bucket,
// leaving the bucket itself. The multipart sweep is not tidiness: a client whose
// upload is refused part by part leaves an upload behind that it cannot list or
// abort through this proxy, and without the sweep the bucket can never be
// deleted (observed with s3cmd, 2026-09-13).
func EmptyBucket(t *testing.T, ctx context.Context, bucket string) {
	t.Helper()
	client := BackendClient(t)

	uploads, err := client.ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{Bucket: aws.String(bucket)})
	if err == nil {
		for _, u := range uploads.Uploads {
			_, abortErr := client.AbortMultipartUpload(ctx, &s3.AbortMultipartUploadInput{
				Bucket: aws.String(bucket), Key: u.Key, UploadId: u.UploadId,
			})
			if abortErr != nil {
				t.Logf("could not abort upload %s of %s: %v", aws.ToString(u.UploadId), aws.ToString(u.Key), abortErr)
			}
		}
	}

	paginator := s3.NewListObjectsV2Paginator(client, &s3.ListObjectsV2Input{Bucket: aws.String(bucket)})
	for paginator.HasMorePages() {
		page, pageErr := paginator.NextPage(ctx)
		if pageErr != nil {
			t.Logf("could not list %s for cleanup: %v", bucket, pageErr)
			return
		}
		for _, obj := range page.Contents {
			if _, delErr := client.DeleteObject(ctx, &s3.DeleteObjectInput{
				Bucket: aws.String(bucket), Key: obj.Key,
			}); delErr != nil {
				t.Logf("could not delete %s: %v", aws.ToString(obj.Key), delErr)
			}
		}
	}

}

// EmptyAndDeleteBucket is EmptyBucket followed by the bucket itself.
func EmptyAndDeleteBucket(t *testing.T, ctx context.Context, bucket string) {
	t.Helper()
	EmptyBucket(t, ctx, bucket)
	if _, delErr := BackendClient(t).DeleteBucket(ctx, &s3.DeleteBucketInput{Bucket: aws.String(bucket)}); delErr != nil {
		t.Logf("could not delete bucket %s: %v", bucket, delErr)
	}
}

// ReadViaProxy returns the plaintext of an object as a client sees it. A suite
// uses it to prove that an object a client reported as corrupted is in fact the
// bytes that client sent.
func ReadViaProxy(t *testing.T, ctx context.Context, bucket, key string) []byte {
	t.Helper()
	out, err := ProxyClient(t).GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket), Key: aws.String(key),
	})
	require.NoErrorf(t, err, "GetObject %s/%s through the proxy", bucket, key)
	defer func() { _ = out.Body.Close() }()
	data, err := io.ReadAll(out.Body)
	require.NoError(t, err)
	return data
}

// OpenUploads returns the upload ids the backend still holds for a bucket. It
// reads the backend directly because a client cannot always see them: under this
// proxy `GET /{bucket}/?uploads` — the form s3cmd sends — is not routed to the
// multipart listing at all.
func OpenUploads(t *testing.T, ctx context.Context, bucket string) []string {
	t.Helper()
	out, err := BackendClient(t).ListMultipartUploads(ctx, &s3.ListMultipartUploadsInput{
		Bucket: aws.String(bucket),
	})
	require.NoErrorf(t, err, "ListMultipartUploads %s on the backend", bucket)

	ids := make([]string, 0, len(out.Uploads))
	for _, u := range out.Uploads {
		ids = append(ids, aws.ToString(u.Key)+"#"+aws.ToString(u.UploadId))
	}
	return ids
}
