//go:build e2e

package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
)

// Outcome is what a client made of a round trip: it either accepted the
// operation or refused it. "Refused" covers every way a client says no — a
// non-zero exit, a reported corruption, a hash it will not vouch for.
type Outcome string

const (
	// Accepts: the client completed the operation and stood behind the result.
	Accepts Outcome = "accepts"
	// Refuses: the client reported the operation as failed or corrupted.
	Refuses Outcome = "refuses"
)

// Case is one row of a client's verdict table: what was run, over which
// endpoint, what the client is expected to make of it today, and — when that
// expectation is Refuses — the defect that expectation pins.
//
// A case whose Expect is Refuses is a defect this product has not answered yet.
// It is recorded rather than skipped: skipping hides it, asserting the answer we
// want makes the suite red on a decision that has not been taken, and neither is
// evidence. When the decision lands, the expectation flips to Accepts and that
// one-line diff is what the release notes point at.
type Case struct {
	ID       string
	Endpoint string
	What     string
	Expect   Outcome
	// Defect names what keeps this case at Refuses, in one line, and cites the
	// ADR the answer belongs in. Required when Expect is Refuses.
	Defect string
}

// Recorder collects the verdicts of one suite and writes them as a table.
type Recorder struct {
	client string
	mu     sync.Mutex
	rows   []row
}

type row struct {
	Case
	Got     Outcome
	Message string
}

// NewRecorder returns the recorder for one client suite. client names the
// binary ("rclone", "s3cmd") and decides the report's file name.
func NewRecorder(client string) *Recorder { return &Recorder{client: client} }

// Record asserts that the client made of this case exactly what the case says
// it makes of it today, and keeps the client's own words for the report.
//
// It fails in BOTH directions on purpose. An unexpected refusal is a regression.
// An unexpected acceptance means the product moved under a decision that is
// still open, and the table and the ADR have to move with it — a
// silently-passing case would let that happen unnoticed.
func (r *Recorder) Record(t *testing.T, c Case, got Outcome, message string) {
	t.Helper()
	require.NotEmptyf(t, c.ID, "a case needs an id")
	if c.Expect == Refuses {
		require.NotEmptyf(t, c.Defect, "case %s expects a refusal and must name the defect it pins", c.ID)
	}

	r.mu.Lock()
	r.rows = append(r.rows, row{Case: c, Got: got, Message: oneLine(message)})
	r.mu.Unlock()

	if c.Expect == Refuses {
		t.Logf("KNOWN DEFECT %s (%s): %s\n  the client says: %s", c.ID, c.Endpoint, c.Defect, oneLine(message))
	}

	require.Equalf(t, c.Expect, got,
		"case %s over %s: %s\nexpected the client to %s, it %s.\n%s\nThe client said:\n%s",
		c.ID, c.Endpoint, c.What, c.Expect, got,
		expectationHint(c), message)
}

func expectationHint(c Case) string {
	if c.Expect == Refuses {
		return "This case pins a known defect: " + c.Defect +
			"\nIf the product now answers it, that is the decision landing: flip this case to Accepts, " +
			"update the ADR it names, and say so in the release notes."
	}
	return "This case asserts behaviour the product is supposed to have. A refusal here is a regression."
}

// Report writes the verdict table. It is called from TestMain after the run, so
// the table describes the whole suite and not whichever case finished last.
func (r *Recorder) Report(dir string) (string, error) {
	r.mu.Lock()
	rows := append([]row(nil), r.rows...)
	r.mu.Unlock()

	if len(rows) == 0 {
		return "", nil
	}
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].ID != rows[j].ID {
			return rows[i].ID < rows[j].ID
		}
		return rows[i].Endpoint < rows[j].Endpoint
	})

	var b strings.Builder
	fmt.Fprintf(&b, "# %s end-to-end verdicts\n\n", r.client)
	fmt.Fprintf(&b, "What %s makes of this proxy, one row per case per endpoint, in the client's own words.\n"+
		"Generated by `make test-e2e-%s`; not committed.\n\n", r.client, r.client)
	b.WriteString("| Case | Endpoint | What it does | Expected | Observed | The client's words |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, x := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			x.ID, x.Endpoint, escapePipes(x.What), x.Expect, x.Got, escapePipes(x.Message))
	}

	var defects []string
	seen := map[string]bool{}
	for _, x := range rows {
		if x.Expect == Refuses && !seen[x.ID+x.Defect] {
			seen[x.ID+x.Defect] = true
			defects = append(defects, fmt.Sprintf("- **%s** — %s", x.ID, x.Defect))
		}
	}
	if len(defects) > 0 {
		b.WriteString("\n## Defects these rows pin\n\n")
		b.WriteString(strings.Join(defects, "\n") + "\n")
	}

	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "e2e-"+r.client+"-verdicts.md")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// oneLine collapses a client's multi-line output to the single line a table can
// hold. The full output is still in the test log on a failure.
func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "(no output)"
	}
	s = strings.Join(strings.Fields(s), " ")
	const maxLen = 220
	if len(s) > maxLen {
		return s[:maxLen] + " …"
	}
	return s
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
