//go:build e2e

package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
)

// Case is one thing a client is driven to do, and the behaviour the product is
// supposed to show when it does it.
//
// Wants is the TARGET, never the answer the product gives today. A case whose
// target is not met fails, and it keeps failing until the product is fixed — a
// red suite is a correct suite, and it is allowed to be committed and to stay
// red. Encoding the current behaviour as the expectation would make a broken
// product report a green pipeline, and a green pipeline says "this may be
// merged", which is the one thing it must not say while the defect is open.
type Case struct {
	ID       string
	Endpoint string
	// What the case does, in the user's vocabulary.
	What string
	// Wants is the behaviour the product must have, in one line, citing the ADR
	// the rule belongs to. It is what a reader of a failure is owed.
	Wants string
}

// Recorder collects what every case observed and writes the table, so a run
// answers "what is still broken" without anyone reading the test tree.
type Recorder struct {
	client string
	mu     sync.Mutex
	rows   []row
}

type row struct {
	Case
	Met     bool
	Message string
}

// NewRecorder returns the recorder for one client suite.
func NewRecorder(client string) *Recorder { return &Recorder{client: client} }

// Want records the observation and then requires that the case's target was met.
// It records BEFORE asserting on purpose: a failing case has to reach the
// report, which is the list of what is left to fix.
//
// met is the caller's judgement that the product did what Wants says. message is
// the client's own words, which is what a failure quotes rather than a
// paraphrase of it.
func (r *Recorder) Want(t *testing.T, c Case, met bool, message string) {
	t.Helper()
	require.NotEmptyf(t, c.ID, "a case needs an id")
	require.NotEmptyf(t, c.Wants, "case %s must say what the product is supposed to do", c.ID)

	r.mu.Lock()
	r.rows = append(r.rows, row{Case: c, Met: met, Message: oneLine(message)})
	r.mu.Unlock()

	require.Truef(t, met,
		"%s over %s — %s\n\nthe product is supposed to: %s\n\nthe client said:\n%s",
		c.ID, c.Endpoint, c.What, c.Wants, message)
}

// Report writes the verdict table and returns how many cases did not meet their
// target, so TestMain can say plainly what is still broken.
func (r *Recorder) Report(dir string) (string, int, error) {
	r.mu.Lock()
	rows := append([]row(nil), r.rows...)
	r.mu.Unlock()

	if len(rows) == 0 {
		return "", 0, nil
	}
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].ID != rows[j].ID {
			return rows[i].ID < rows[j].ID
		}
		return rows[i].Endpoint < rows[j].Endpoint
	})

	var broken []row
	for _, x := range rows {
		if !x.Met {
			broken = append(broken, x)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s end-to-end verdicts\n\n", r.client)
	fmt.Fprintf(&b, "What %s makes of this proxy, one row per case per endpoint, in the client's own\n"+
		"words. Every row states the behaviour the product is supposed to have; a row that is\n"+
		"not met is a defect that is still open, never an accepted deviation.\n"+
		"Generated by `make test-e2e-%s`; not committed.\n\n", r.client, r.client)

	if len(broken) > 0 {
		fmt.Fprintf(&b, "## Still broken — %d of %d cases\n\n", len(broken), len(rows))
		for _, x := range broken {
			fmt.Fprintf(&b, "- **%s** (%s) — %s\n  - supposed to: %s\n  - %s said: %s\n",
				x.ID, x.Endpoint, x.What, x.Wants, r.client, x.Message)
		}
		b.WriteString("\n")
	} else {
		fmt.Fprintf(&b, "## All %d cases met their target\n\n", len(rows))
	}

	b.WriteString("## Every case\n\n")
	b.WriteString("| Case | Endpoint | What it does | Supposed to | Met | The client's words |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, x := range rows {
		met := "yes"
		if !x.Met {
			met = "**NO**"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			x.ID, x.Endpoint, escapePipes(x.What), escapePipes(x.Wants), met, escapePipes(x.Message))
	}

	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", len(broken), err
	}
	path := filepath.Join(dir, "e2e-"+r.client+"-verdicts.md")
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", len(broken), err
	}
	return path, len(broken), nil
}

// Summary is the short list a continuous-integration step summary carries, so a
// red check names the defects without anyone opening an artifact.
func (r *Recorder) Summary() string {
	r.mu.Lock()
	rows := append([]row(nil), r.rows...)
	r.mu.Unlock()

	var broken []row
	for _, x := range rows {
		if !x.Met {
			broken = append(broken, x)
		}
	}
	if len(broken) == 0 {
		return fmt.Sprintf("### %s end-to-end: all %d cases met their target\n", r.client, len(rows))
	}
	sort.SliceStable(broken, func(i, j int) bool {
		if broken[i].ID != broken[j].ID {
			return broken[i].ID < broken[j].ID
		}
		return broken[i].Endpoint < broken[j].Endpoint
	})

	var b strings.Builder
	fmt.Fprintf(&b, "### %s end-to-end: %d of %d cases still broken\n\n", r.client, len(broken), len(rows))
	b.WriteString("| Case | Endpoint | Supposed to | What it does instead |\n|---|---|---|---|\n")
	for _, x := range broken {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			x.ID, x.Endpoint, escapePipes(x.Wants), escapePipes(x.Message))
	}
	return b.String()
}

// oneLine collapses a client's multi-line output to the single line a table can
// hold. The full output is still in the test log on a failure.
func oneLine(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "(no output)"
	}
	s = strings.Join(strings.Fields(s), " ")
	const maxLen = 220
	if len(s) > maxLen {
		return s[:maxLen] + " …"
	}
	return s
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// WriteStepSummary appends text to the continuous-integration step summary when
// one is set, so a red check names the defects on the pull request itself
// instead of only in an artifact. A no-op outside CI.
func WriteStepSummary(text string) {
	path := os.Getenv("GITHUB_STEP_SUMMARY")
	if path == "" {
		return
	}
	// #nosec G703 -- the path is the runner's own GITHUB_STEP_SUMMARY, not input
	fh, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0o600)
	if err != nil {
		return
	}
	defer func() { _ = fh.Close() }()
	_, _ = fmt.Fprintf(fh, "%s\n", text)
}
