//go:build e2e

package velero

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/stretchr/testify/require"

	"github.com/guided-traffic/s3-encryption-proxy/test/e2e/harness"
)

// backendClient talks to MinIO directly, bypassing the proxy. It is how the
// suite proves objects are stored encrypted: everything it reads is exactly what
// is on disk in the backend.
func backendClient(t *testing.T) *s3.Client {
	t.Helper()
	e := loadVersionsEnv(t)
	endpoint := fmt.Sprintf("https://127.0.0.1:%s", e.get(t, "MINIO_NODEPORT"))

	cfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			e.get(t, "MINIO_ROOT_USER"), e.get(t, "MINIO_ROOT_PASSWORD"), "")),
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithHTTPClient(caTrustingHTTPClient(t)),
	)
	require.NoError(t, err)

	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
	})
}

// proxyClient talks to the proxy over its NodePort, i.e. the same path Velero's
// pre-signed URLs point at. Objects read through it come back decrypted.
func proxyClient(t *testing.T) *s3.Client {
	t.Helper()
	e := loadVersionsEnv(t)
	endpoint := fmt.Sprintf("https://127.0.0.1:%s", e.get(t, "PROXY_NODEPORT"))

	cfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			e.get(t, "PROXY_CLIENT_ACCESS_KEY"), e.get(t, "PROXY_CLIENT_SECRET_KEY"), "")),
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithHTTPClient(caTrustingHTTPClient(t)),
	)
	require.NoError(t, err)

	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
	})
}

// caTrustingHTTPClient trusts the CA generated by test/ssl-setup/gen-certs.sh.
// Verification is deliberately on: the proxy certificate is part of what the
// suite validates, and Velero itself validates it through the BSL caCert.
func caTrustingHTTPClient(t *testing.T) *http.Client {
	t.Helper()
	pemBytes, err := os.ReadFile(filepath.Join(repoRoot(t), "test", "ssl-setup", "ca.crt"))
	require.NoError(t, err, "test CA not found; run test/ssl-setup/gen-certs.sh")

	pool := x509.NewCertPool()
	require.True(t, pool.AppendCertsFromPEM(pemBytes), "test CA is not parseable")

	return &http.Client{
		Timeout: 5 * time.Minute,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12},
		},
	}
}

// backendObject is one stored object as the backend sees it. The listing and the
// at-rest assertion are shared with the client end-to-end suites, so the type is
// theirs; this suite supplies its own client and bucket, which live in a kind
// cluster rather than on the demo compose stack.
type backendObject = harness.StoredObject

// listBackendObjects returns every object under prefix, with the user metadata
// the proxy attached.
func listBackendObjects(t *testing.T, ctx context.Context, prefix string) []backendObject {
	t.Helper()
	return harness.ListStored(t, ctx, backendClient(t), veleroBucket(t), prefix)
}

// veleroBucket is the bucket this suite's Velero writes into.
func veleroBucket(t *testing.T) string {
	t.Helper()
	return loadVersionsEnv(t).get(t, "VELERO_BUCKET")
}

// readBackendObject returns the raw stored bytes of an object, ciphertext
// included.
func readBackendObject(t *testing.T, ctx context.Context, key string) []byte {
	t.Helper()
	return harness.ReadStored(t, ctx, backendClient(t), veleroBucket(t), key)
}

// readViaProxy returns the plaintext of an object as a client sees it.
func readViaProxy(t *testing.T, ctx context.Context, key string) []byte {
	t.Helper()
	bucket := loadVersionsEnv(t).get(t, "VELERO_BUCKET")
	out, err := proxyClient(t).GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	require.NoErrorf(t, err, "GetObject %s through the proxy", key)
	defer func() { _ = out.Body.Close() }()

	data, err := io.ReadAll(out.Body)
	require.NoError(t, err)
	return data
}
