//go:build e2e

package velero

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/stretchr/testify/require"
)

// backendClient talks to MinIO directly, bypassing the proxy. It is how the
// suite proves objects are stored encrypted: everything it reads is exactly what
// is on disk in the backend.
func backendClient(t *testing.T) *s3.Client {
	t.Helper()
	e := loadVersionsEnv(t)
	endpoint := fmt.Sprintf("https://127.0.0.1:%s", e.get(t, "MINIO_NODEPORT"))

	cfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			e.get(t, "MINIO_ROOT_USER"), e.get(t, "MINIO_ROOT_PASSWORD"), "")),
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithHTTPClient(caTrustingHTTPClient(t)),
	)
	require.NoError(t, err)

	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
	})
}

// proxyClient talks to the proxy over its NodePort, i.e. the same path Velero's
// pre-signed URLs point at. Objects read through it come back decrypted.
func proxyClient(t *testing.T) *s3.Client {
	t.Helper()
	e := loadVersionsEnv(t)
	endpoint := fmt.Sprintf("https://127.0.0.1:%s", e.get(t, "PROXY_NODEPORT"))

	cfg, err := awsconfig.LoadDefaultConfig(context.Background(),
		awsconfig.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			e.get(t, "PROXY_CLIENT_ACCESS_KEY"), e.get(t, "PROXY_CLIENT_SECRET_KEY"), "")),
		awsconfig.WithRegion("us-east-1"),
		awsconfig.WithHTTPClient(caTrustingHTTPClient(t)),
	)
	require.NoError(t, err)

	return s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
	})
}

// caTrustingHTTPClient trusts the CA generated by test/ssl-setup/gen-certs.sh.
// Verification is deliberately on: the proxy certificate is part of what the
// suite validates, and Velero itself validates it through the BSL caCert.
func caTrustingHTTPClient(t *testing.T) *http.Client {
	t.Helper()
	pemBytes, err := os.ReadFile(filepath.Join(repoRoot(t), "test", "ssl-setup", "ca.crt"))
	require.NoError(t, err, "test CA not found; run test/ssl-setup/gen-certs.sh")

	pool := x509.NewCertPool()
	require.True(t, pool.AppendCertsFromPEM(pemBytes), "test CA is not parseable")

	return &http.Client{
		Timeout: 5 * time.Minute,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12},
		},
	}
}

// backendObject is one stored object as the backend sees it.
type backendObject struct {
	Key      string
	Size     int64
	Metadata map[string]string
}

// listBackendObjects returns every object under prefix, with the user metadata
// the proxy attached.
func listBackendObjects(t *testing.T, ctx context.Context, prefix string) []backendObject {
	t.Helper()
	client := backendClient(t)
	bucket := loadVersionsEnv(t).get(t, "VELERO_BUCKET")

	var objects []backendObject
	paginator := s3.NewListObjectsV2Paginator(client, &s3.ListObjectsV2Input{
		Bucket: aws.String(bucket),
		Prefix: aws.String(prefix),
	})
	for paginator.HasMorePages() {
		page, err := paginator.NextPage(ctx)
		require.NoError(t, err, "listing %s/%s on the backend", bucket, prefix)
		for _, obj := range page.Contents {
			head, err := client.HeadObject(ctx, &s3.HeadObjectInput{
				Bucket: aws.String(bucket),
				Key:    obj.Key,
			})
			require.NoErrorf(t, err, "HeadObject %s", aws.ToString(obj.Key))
			objects = append(objects, backendObject{
				Key:      aws.ToString(obj.Key),
				Size:     aws.ToInt64(obj.Size),
				Metadata: head.Metadata,
			})
		}
	}
	return objects
}

// readBackendObject returns the raw stored bytes of an object, ciphertext
// included.
func readBackendObject(t *testing.T, ctx context.Context, key string) []byte {
	t.Helper()
	bucket := loadVersionsEnv(t).get(t, "VELERO_BUCKET")
	out, err := backendClient(t).GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	require.NoErrorf(t, err, "GetObject %s from the backend", key)
	defer func() { _ = out.Body.Close() }()

	data, err := io.ReadAll(out.Body)
	require.NoError(t, err)
	return data
}

// readViaProxy returns the plaintext of an object as a client sees it.
func readViaProxy(t *testing.T, ctx context.Context, key string) []byte {
	t.Helper()
	bucket := loadVersionsEnv(t).get(t, "VELERO_BUCKET")
	out, err := proxyClient(t).GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	require.NoErrorf(t, err, "GetObject %s through the proxy", key)
	defer func() { _ = out.Body.Close() }()

	data, err := io.ReadAll(out.Body)
	require.NoError(t, err)
	return data
}

// hasEncryptionMetadata reports whether the proxy recorded envelope-encryption
// metadata on the object. AWS lower-cases metadata keys, so the comparison is
// case-insensitive.
func hasEncryptionMetadata(meta map[string]string, prefix string) bool {
	for k := range meta {
		if strings.HasPrefix(strings.ToLower(k), prefix) {
			return true
		}
	}
	return false
}

// metadataValue returns a metadata value by suffix, ignoring case.
func metadataValue(meta map[string]string, prefix, suffix string) (string, bool) {
	want := strings.ToLower(prefix + suffix)
	for k, v := range meta {
		if strings.ToLower(k) == want {
			return v, true
		}
	}
	return "", false
}
